name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Ini akan berjalan ketika ada push ke branch "main"
      - main  
  pull_request:
    branches:
      - master  # Ini akan berjalan ketika ada pull request ke branch "main"
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Step 3: Get current datetime
    - name: Get current datetime
      id: datetime
      run: echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    # Step 4: Build the Docker image with datetime tag
    - name: Build Docker image API
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/olshop:${{ env.DATETIME }} -f Dockerfile .

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image API
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/olshop:${{ env.DATETIME }}
